version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: sportsnotes
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=sportsnoted
      - MYSQL_USER=admin
      - MYSQL_PASS=admin
      - MYSQL_DB=db_sportsnotes
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:8005"
    container_name: moe-nodejs-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=db_sportsnotes
    container_name: sportsnotes
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=sportsnotes
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: sportsnotes-phpmyadmin-app
networks:
  frontend:
  backend:
